[versions]
agp = "9.4.1"
appcompat = "1.8.0"
play-services-maps = "20.0.0"
play-services-base = "18.11.0"
constraintlayout = "2.2.2"
material = "1.14.0"
navigation = "2.10.2"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "play-services-base" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }