[versions]
agp = "9.4.1"
appcompat = "1.8.0"
material = "1.14.0"
constraintlayout = "2.2.2"
activity = "1.13.0"
face-detection = "16.1.7"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "face-detection" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
