[versions]
agp = "9.4.1"
appcompat = "1.8.0"
material = "1.14.0"
constraintlayout = "2.2.2"
activity = "1.13.0"
play-services-code-scanner = "16.1.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "play-services-code-scanner" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
